#!/usr/bin/env bash

# Bash script that transfers a file from our client to server

PATH_TO_FILE="$2"
IP="$3"
USERNAME="$4"
PATH_TO_SSH_KEY="$5"

if [[ $# -lt 3 ]]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
else
	scp "$PATH_TO_FILE" "$USERNAME"@"$IP":~"$PATH_TO_SSH_KEY"
fi
