#!/usr/bin/env bash
# Redirection configured as a 307 moved permanently

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
	listen 80;
	listen	[::]:80 default_server;
	root	/etc/nginx/html;
	location	/redirect_me {
		return 307 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}" > /etc/nginx/sites-available/default

service nginx restart
