#!/usr/bin/env bash
# Custom error 404 message

apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
printf %s "server {
	listen 80;
	listen	[::]:80 default_server;
	add_header X-Served-By $HOSTNAME;
	root	/var/www/html;
	index	index.html index.htm;
	location	/redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

	error_page 404 /404.html;
	location /404 {
		root /var/www/html;
		internal;
	}
}" > /etc/nginx/sites-available/default

service nginx restart
