#!/usr/bin/env bash
# installing and configuring HAProxy on my lb-01 server

balance="\
frontend haproxy_balancer
	bind *:80
	mode http
	default_backend webservers

backend webservers
	balance roundrobin
	server	171105-web-01 54.90.15.228 check
	server	171105-web-02 35.153.66.157 check
"

# updating packages
apt-get update -y
apt-get -y upgrade

# Adding HAProxy PPA
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

# Installing HAProxy
apt-get -y haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balance" >> /etc/haproxy/haproxy.cfg
service haproxy restart
